apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-to-pdf-converter
  labels:
    app: doc-to-pdf-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doc-to-pdf-converter
  template:
    metadata:
      labels:
        app: doc-to-pdf-converter
    spec:
      containers:
      - name: doc-to-pdf-converter
        image: gcr.io/YOUR_PROJECT_ID/doc-to-pdf-converter:latest
        ports:
        - containerPort: 8080
        env:
        - name: BUCKET_NAME
          value: "YOUR_PROJECT_ID-pdf-assets"
        - name: GOOGLE_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: google-credentials
              key: credentials.json
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: doc-to-pdf-service
spec:
  selector:
    app: doc-to-pdf-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  credentials.json: BASE64_ENCODED_SERVICE_ACCOUNT_KEY

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: doc-to-pdf-ssl-cert
spec:
  domains:
    - your-domain.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doc-to-pdf-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "doc-to-pdf-ip"
    networking.gke.io/managed-certificates: "doc-to-pdf-ssl-cert"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: doc-to-pdf-service
            port:
              number: 80